ping www.qq.com > record.txt
ping www.qqmail.com >> record.txt
ping www.soso.com >> record.txt
ping www.tencent.com >> record.txt
ping www.paipai.com >> record.txt
ping www.microsoft.com >> record.txt
ping www.windowsupdate.com >> record.txt
ping www.live.com >> record.txt
ping www.msn.com >> record.txt
ping www.gmodules.com >> record.txt
ping www.google.com >> record.txt
ping www.googleadsserving.com >> record.txt
ping www.google-analytics.com >> record.txt
ping www.gstatic.cn >> record.txt
ping www.laibafile.cn >> record.txt
ping www.7sou.com >> record.txt
ping www.gvt0.com >> record.txt
ping www.shuqi.com >> record.txt
ping www.renren.com >> record.txt
ping www.xiaonei.com >> record.txt
ping www.baidu.com >> record.txt
ping www.channelray.com >> record.txt
ping www.yicha.cn >> record.txt
ping www.360.com >> record.txt
ping www.360safe.com >> record.txt
ping www.itc.gov.hk >> record.txt
ping www.adobe.com >> record.txt
ping www.macromedia.com >> record.txt
ping www.symantec.com >> record.txt
ping www.symantecliveupdate.com >> record.txt
ping www.3g.cn >> record.txt
ping www.uc.cn >> record.txt
ping www.ucweb.com >> record.txt
ping www.xunlei.com >> record.txt
ping www.gougou.com >> record.txt
ping www.n-gage.com >> record.txt
ping www.nokia.com >> record.txt
ping www.poi.com >> record.txt
ping www.mop.com >> record.txt
ping www.10jqka.com.cn >> record.txt
ping www.pp.cn >> record.txt
ping www.wappp.com >> record.txt
ping www.126.com >> record.txt
ping www.163.com >> record.txt
ping www.netease.com >> record.txt
ping www.zhi3.com >> record.txt
ping www.tianya.cn >> record.txt
ping www.17173.com >> record.txt
ping www.sohu.com >> record.txt
ping www.chinaren.com >> record.txt
ping www.focus.cn >> record.txt
ping www.iask.com >> record.txt
ping www.sina.com >> record.txt
ping www.taobao.com >> record.txt
ping www.apple.com >> record.txt
ping www.doubleclick.com >> record.txt
ping www.map.com.tw >> record.txt
ping www.joy.cn >> record.txt
ping www.megajoy.com >> record.txt
ping www.cctv.com >> record.txt
ping www.4399.com >> record.txt
ping www.easou.com >> record.txt
ping www.7k7k.com >> record.txt
ping www.duba.com >> record.txt
ping www.netqin.com >> record.txt
ping www.51mole.com >> record.txt
ping www.youku.com >> record.txt
ping www.uodoo.cn >> record.txt
ping www.16kxs.com >> record.txt
ping www.rising.com.cn >> record.txt
ping www.rayfile.com >> record.txt
ping www.115.com >> record.txt
ping www.eastmoney.com >> record.txt
ping www.dospy.com >> record.txt
ping www.waptw.com >> record.txt
ping www.alimama.com >> record.txt
ping www.sogou.com >> record.txt
ping www.aapig.com >> record.txt
ping www.kuwo.cn >> record.txt
ping www.koowo.com >> record.txt
ping www.baofeng.com >> record.txt
ping www.mochiads.com >> record.txt
ping www.feiku.com >> record.txt
ping www.ku6.com >> record.txt
ping www.uusee.com >> record.txt
ping www.jrj.com.cn >> record.txt
ping www.huohuo.com >> record.txt
ping www.tudou.com >> record.txt
ping www.duote.com >> record.txt
ping www.duotegame.com >> record.txt
ping www.weather.com.cn >> record.txt
ping www.jiayuan.com >> record.txt
ping www.lexun.com >> record.txt
ping www.china.com >> record.txt
ping www.autohome.com >> record.txt
ping www.tiancity.com >> record.txt
ping www.qianqian.com >> record.txt
ping www.ppstream.com >> record.txt
ping www.kaixin001.com >> record.txt
ping www.kaixin.com >> record.txt
ping www.xinhuanet.com >> record.txt
ping www.news.cn >> record.txt
ping www.pplive.com >> record.txt
ping www.zhaopin.com >> record.txt
ping www.funshion.com >> record.txt
ping www.zol.com >> record.txt
ping www.zol-img.com >> record.txt
ping www.ifeng.com >> record.txt
ping www.kxting.com >> record.txt
ping www.babidou.com >> record.txt
ping www.douxie.com >> record.txt
ping mini.opera.com >> record.txt
ping www.xiaoxiaoshuo.net >> record.txt
ping www.sdo.com >> record.txt
ping www.gametea.com >> record.txt
ping www.qq908.cn >> record.txt
ping www.fminutes.com >> record.txt
ping www.kunlun.com >> record.txt
ping www.360buy.com >> record.txt
ping www.yxdown.com >> record.txt
ping 10086.cn >> record.txt
ping music.10086.cn >> record.txt
ping www.qidian.com >> record.txt
ping us.blizzard.com >> record.txt
ping www.qunar.com >> record.txt
ping www.allyes.com >> record.txt
ping www.coopen.cn >> record.txt
ping www.micat.com >> record.txt
ping www.youxi369.com >> record.txt
ping cn.yahoo.com >> record.txt
ping www.eebbk.com >> record.txt
ping www.pconline.com.cn >> record.txt
ping www.51.com >> record.txt
ping www.51img1.com >> record.txt
ping www.game2.cn >> record.txt
ping www.5sing.com >> record.txt
ping www.iciba.com >> record.txt
ping www.pchome.net >> record.txt
ping www.letv.com >> record.txt
ping u.9wee.com >> record.txt
ping my.4399.com >> record.txt
ping www.1000chi.com >> record.txt
ping xa.58.com >> record.txt
ping www.verycd.com >> record.txt
ping www.bokecc.com >> record.txt
ping www.ghostxp2.com >> record.txt
ping www.91.com >> record.txt
ping www.people.com.cn >> record.txt
ping zyxmmovie.mtime.com >> record.txt
ping www.kuxun.cn >> record.txt
ping www.wanyx.com >> record.txt
ping www.slide.com >> record.txt
ping www.3gyy.net.cn >> record.txt
ping www.eset.com.cn >> record.txt
ping www.hexun.com >> record.txt
ping www.51coolbar.com >> record.txt
ping www.duowan.com >> record.txt
ping www.lelewan.com >> record.txt
ping www.oppo.com >> record.txt
ping www.56.com >> record.txt
ping xian.bitauto.com  >> record.txt
ping www.80s.cn >> record.txt
ping www.gyyx.cn >> record.txt
ping www.sjxyx.com >> record.txt
ping www.9you.com >> record.txt
ping www.xici.net >> record.txt
ping www.maxthon.cn >> record.txt
ping www.xiazaiba.com >> record.txt
ping www.wanmei.com >> record.txt
ping www.3839.com >> record.txt
ping www.huanqiu.com >> record.txt
ping www.ttpod.com >> record.txt
ping www.ganji.com >> record.txt
ping www.lenovo.com.cn >> record.txt
ping www.blovestorm.com >> record.txt
ping www.tx8.cn >> record.txt
ping www.chinaacc.com >> record.txt
ping www.dell.com.cn >> record.txt
ping www.skycn.com >> record.txt
ping www.soufun.com >> record.txt
ping www.rekoo.com >> record.txt
ping www.aipai.com >> record.txt
ping www.shangdu.com >> record.txt
ping www.pu.edu.tw >> record.txt
ping www.kaspersky.com >> record.txt
ping www.jaguar.net >> record.txt
ping www.hao123.com >> record.txt
ping www.readnovel.com >> record.txt
ping www.it168.com >> record.txt
ping www.hinet.net >> record.txt
ping www.newyx.net >> record.txt
ping www.zdface.com >> record.txt
ping www.juedui100.com >> record.txt
ping www.hunantv.com >> record.txt
ping www.webgame.com.cn >> record.txt
ping www.baihe.net >> record.txt
ping cn.trendmicro.com >> record.txt
ping www.akamai.cn >> record.txt
ping www.kdnet.net >> record.txt
ping www.mapabc.com >> record.txt
ping www.youdao.com >> record.txt
ping www.kugou.com >> record.txt
ping www.hp.com >> record.txt
ping www.91danji.com >> record.txt
ping www.onlylady.com >> record.txt
ping www.titan24.com >> record.txt
ping www.91wan.com >> record.txt
ping www.daqi.com.cn >> record.txt
ping www.feedburner.com >> record.txt
ping www.titan007.com >> record.txt
ping fzlzt.net >> record.txt
ping www.VANCL.com  >> record.txt
ping www.game5.com >> record.txt
ping www.3conline.net >> record.txt
ping www.nakido.com >> record.txt
ping www.rayli.com.cn >> record.txt
ping www.mbook.com.cn >> record.txt
ping www.vietvideo.com >> record.txt
ping www.wix.com.cn >> record.txt
ping www.the9.com >> record.txt
ping www.vodone.com >> record.txt
ping www.crsky.com >> record.txt
ping www.usaupload.net >> record.txt
ping www.qingdaonews.com >> record.txt
ping hunan.voc.com.cn >> record.txt
ping www.quxiu.com >> record.txt
ping 6.cn >> record.txt
ping www.enet.com.cn >> record.txt
ping www.lvxiang.com.cn >> record.txt
ping www.2144.cn >> record.txt
ping 8zntx.com >> record.txt
ping www.caike.com >> record.txt
ping lover2.net >> record.txt
ping www.oracle.com >> record.txt
ping www.0-6.com >> record.txt
ping ruanh.com >> record.txt
ping www.indabamusic.com >> record.txt
ping www.onlinedown.net >> record.txt
ping www.91rb.com >> record.txt
ping www.aibang.com >> record.txt
ping www.cnki.net >> record.txt
ping www.83suncity.com >> record.txt
ping www.nai.edu.cn >> record.txt
ping www.haoting.com >> record.txt
ping www.50888.com >> record.txt
ping www.newding.com >> record.txt
ping www.ChinaHR.com >> record.txt
ping www.yupoo.com >> record.txt
ping www.cnzz.com >> record.txt
ping www.ztgame.com >> record.txt
ping www.hongxiu.com >> record.txt
ping www.d.cn >> record.txt
ping www.moscreen.cn >> record.txt
ping 5gdj.com >> record.txt
ping www.27.cn >> record.txt
ping www.myspace.cn >> record.txt
ping www.txdzs.com >> record.txt
ping www.703804.com >> record.txt
ping www.pcpop.com >> record.txt
ping www.ynet.com >> record.txt
ping www.sjdzs.com >> record.txt
ping www.mcafee.com >> record.txt
ping www.178.com >> record.txt
ping www.17k.com >> record.txt
ping www.bitdefender.com >> record.txt
ping www.zhcatv.com >> record.txt
